services:
  - type: web
    name: iyuup-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: iyuup-db
          property: connectionString
      - key: HYPERSWITCH_API_KEY
        sync: false
      - key: HYPERSWITCH_PUBLISHABLE_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: iyuup-db
    databaseName: iyuup
    user: iyuup_user